# Generated by Django 4.1.2 on 2022-10-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
