# Generated by Django 4.1.2 on 2022-10-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_incidentreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='date',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='incidentDepartment',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='time',
            field=models.TimeField(blank=True, default=None),
        ),
    ]
