# Generated by Django 4.1.2 on 2022-10-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_incidentreport_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='location',
            field=models.CharField(blank=True, choices=[('Corporate Headoffice', 'Corporate Headoffice'), ('Operations Department', 'Operations Department'), ('Work Station', 'Work Station'), ('Marketing Division', 'Marketing Division')], default=None, max_length=30, null=True),
        ),
    ]
