# Generated by Django 4.1.2 on 2022-10-15 16:10

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_incidentreport_subincidenttypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='immediateAction',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='incidentDepartment',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='incidentLocation',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='subIncidentTypes',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Environmental Incident', 'Environmental Incident'), ('Injury/Illness', 'Injury/Illness'), ('Property Damage', 'Property Damage'), ('Vehicle', 'Vehicle')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='suspectedCause',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='time',
            field=models.TimeField(default=None, null=True),
        ),
    ]
